const today = "2026-08-31";
export const defaultProfile = {
  avatar: "",
  email: "leader@example.com",
  region: "桃園市",
  serviceAreas: ["台灣北部", "日本"],
  languages: ["中文", "台語", "日文"],
  tourCount: 3,
  bio: "具備國內外帶團經驗，擅長掌握行程節奏及協助旅客處理突發狀況。帶團風格親切、有耐心，重視每一位旅客的旅遊體驗。",
  styles: ["親切活潑", "行程掌控", "緊急應變"],
  travelTypes: ["日本旅遊", "企業參訪", "員工旅遊"],
  tags: ["日本線", "企業團", "親子旅遊"],
  experiences: [
    {
      id: "exp-1",
      name: "北海道賞雪5日",
      agency: "晴日旅行社",
      region: "日本北海道",
      start: "2026-02-10",
      end: "2026-02-14",
      people: 32,
      role: "領隊",
      description: "冬季雪地行程與突發天候應變。",
    },
    {
      id: "exp-2",
      name: "台積電企業參訪3日",
      agency: "星辰國際旅行社",
      region: "台灣北部",
      start: "2026-05-18",
      end: "2026-05-20",
      people: 25,
      role: "領隊",
      description: "企業參訪接待與流程控管。",
    },
  ],
  gallery: [],
  certificateNote: "具備日本線與企業參訪團帶團經驗。",
  certificateNumber: "A12****89",
  certificateStatus: "已通過",
  certificateExpiry: "2028-12-31",
  privacy: {
    phone: false,
    email: false,
    birthday: false,
    region: true,
    experiences: true,
    gallery: true,
    certificateStatus: true,
    invite: true,
  },
};
export const defaultJobs = [
  {
    id: "job-001",
    title: "北海道賞雪團領隊",
    agencyId: "sunny",
    agencyName: "晴日旅行社",
    role: "leader",
    roleLabel: "領隊",
    category: "海外帶團",
    destination: "日本北海道",
    area: "日本",
    meetingLocation: "桃園國際機場第二航廈",
    startDate: "2026-12-10",
    endDate: "2026-12-14",
    days: 5,
    openings: 2,
    salary: 3500,
    salaryLabel: "NT$3,500／日",
    salaryType: "日薪",
    deadline: "2026-11-20",
    featured: true,
    status: "open",
    publishedAt: "2026-08-31",
    tags: ["日本線", "賞雪團", "提供住宿"],
    summary: "帶領北海道冬季賞雪團，協助旅客安全完成行程。",
  },
  {
    id: "job-002",
    title: "沖繩親子旅遊導遊",
    agencyId: "island",
    agencyName: "島嶼探索旅遊",
    role: "guide",
    roleLabel: "導遊",
    category: "親子旅遊",
    destination: "日本沖繩",
    area: "日本",
    meetingLocation: "那霸機場",
    startDate: "2026-10-03",
    endDate: "2026-10-06",
    days: 4,
    openings: 1,
    salary: 16000,
    salaryLabel: "NT$16,000／團",
    salaryType: "團費",
    deadline: "2026-09-15",
    featured: true,
    status: "open",
    publishedAt: "2026-08-29",
    tags: ["沖繩", "親子團", "在地導覽"],
    summary: "親子友善路線導覽與景點故事解說。",
  },
  {
    id: "job-003",
    title: "台積電企業參訪領隊",
    agencyId: "star",
    agencyName: "星辰國際旅行社",
    role: "leader",
    roleLabel: "領隊",
    category: "企業參訪",
    destination: "新竹",
    area: "台灣北部",
    meetingLocation: "台北車站東三門",
    startDate: "2026-09-22",
    endDate: "2026-09-24",
    days: 3,
    openings: 3,
    salary: 3200,
    salaryLabel: "NT$3,200／日",
    salaryType: "日薪",
    deadline: "2026-09-10",
    featured: true,
    status: "open",
    publishedAt: "2026-08-30",
    tags: ["企業團", "參訪", "流程管理"],
    summary: "企業參訪接待、集合與每日行程回報。",
  },
  {
    id: "job-004",
    title: "桃園一日文化導覽",
    agencyId: "taoyuan",
    agencyName: "桃園樂遊旅行社",
    role: "guide",
    roleLabel: "導遊",
    category: "國內導覽",
    destination: "桃園",
    area: "台灣北部",
    meetingLocation: "桃園火車站",
    startDate: "2026-10-18",
    endDate: "2026-10-18",
    days: 1,
    openings: 2,
    salary: 4000,
    salaryLabel: "NT$4,000／日",
    salaryType: "日薪",
    deadline: "2026-10-05",
    featured: false,
    status: "open",
    publishedAt: "2026-08-26",
    tags: ["文化導覽", "一日遊"],
    summary: "桃園舊城區與文化景點在地導覽。",
  },
  {
    id: "job-005",
    title: "韓國賞楓團隨團領隊",
    agencyId: "sunny",
    agencyName: "晴日旅行社",
    role: "leader",
    roleLabel: "領隊",
    category: "海外帶團",
    destination: "韓國首爾",
    area: "韓國",
    meetingLocation: "桃園機場第一航廈",
    startDate: "2026-11-02",
    endDate: "2026-11-07",
    days: 6,
    openings: 1,
    salary: 3600,
    salaryLabel: "NT$3,600／日",
    salaryType: "日薪",
    deadline: "2026-09-28",
    featured: false,
    status: "open",
    publishedAt: "2026-08-25",
    tags: ["韓國", "賞楓"],
    summary: "韓國秋季團體行程執行與旅客服務。",
  },
  {
    id: "job-006",
    title: "台北城市散步英語導覽",
    agencyId: "island",
    agencyName: "島嶼探索旅遊",
    role: "both",
    roleLabel: "領隊／導遊",
    category: "城市導覽",
    destination: "台北",
    area: "台灣北部",
    meetingLocation: "捷運中山站",
    startDate: "2026-09-12",
    endDate: "2026-09-12",
    days: 1,
    openings: 4,
    salary: 650,
    salaryLabel: "NT$650／時",
    salaryType: "時薪",
    deadline: "2026-09-08",
    featured: false,
    status: "open",
    publishedAt: "2026-08-28",
    tags: ["英語", "城市散步"],
    summary: "以英語帶領外籍旅客探索台北街區。",
  },
];
const postSeeds = [
  ["北海道冬季暴雪備案分享", "突發狀況", "日本北海道"],
  ["日本遊覽車行李規定更新", "行程情報", "日本"],
  ["企業參訪團帶團注意事項", "帶團經驗", "台灣"],
  ["新手領隊如何準備行前說明會？", "工作交流", "台灣"],
  ["日文導遊證考試準備方向", "證照考試", "日本"],
  ["桃園機場團體集合位置經驗分享", "景點交通", "桃園"],
  ["沖繩親子團餐廳安排心得", "帶團經驗", "日本沖繩"],
  ["歐洲跨國團網路與聯絡準備", "海外情報", "歐洲"],
  ["旅客護照遺失的處理流程", "突發狀況", "海外"],
  ["韓國賞楓季巴士預約提醒", "行程情報", "韓國"],
];
export const defaultPosts = Array.from({ length: 20 }, (_, i) => {
  const s = postSeeds[i % postSeeds.length];
  return {
    id: `post-${String(i + 1).padStart(3, "0")}`,
    authorId: i % 5 === 0 ? "demo-user" : `user-${i}`,
    authorName:
      i % 5 === 0
        ? "吳小幫手"
        : ["林怡君", "陳柏翰", "王美玲", "晴日旅行社"][i % 4],
    authorType: i % 4 === 3 ? "agency" : i % 2 ? "guide" : "leader",
    verified: true,
    postType: i % 4 === 0 ? "question" : "story",
    category: s[1],
    title: i < 10 ? s[0] : `${s[0]}｜實務補充 ${i - 9}`,
    content:
      "這篇整理實際帶團時的重要準備、現場判斷與溝通方式。建議出發前再次確認交通、天候與旅行社緊急聯絡窗口，並保留彈性備案。",
    excerpt: "整理實際帶團的重要準備、現場判斷與溝通方式。",
    region: s[2],
    tags: [s[1], s[2], "帶團實務"],
    views: 98 + i * 17,
    likedBy: [],
    bookmarkedBy: [],
    bestAnswerId: null,
    status: "published",
    isPinned: i === 0,
    createdAt: `2026-08-${String(31 - (i % 20)).padStart(2, "0")}`,
    updatedAt: "",
  };
});
export const defaultComments = [
  {
    id: "comment-001",
    postId: "post-001",
    authorId: "user-2",
    authorName: "林怡君",
    content: "我會先確認替代景點是否開放，並同步通知司機與旅行社窗口。",
    likedBy: [],
    parentId: null,
    createdAt: "2026-08-31 10:20",
  },
];
const incomeSeeds = [
  [
    "旅遊文章創作者募集",
    "文章投稿",
    "旅遊資訊合作中心",
    "每篇 NT$800～2,000",
    "分享實際帶團經驗或景點情報",
  ],
  [
    "日本行程顧問合作計畫",
    "行程顧問",
    "晴日旅行社",
    "每案 NT$2,000～5,000",
    "提供日本線行程與交通建議",
  ],
  [
    "旅遊商品推薦分潤",
    "商品推薦",
    "旅遊選品平台",
    "每筆訂單 5%～12%",
    "分享旅遊用品專屬推薦連結",
  ],
  [
    "北海道冬季情報投稿",
    "文章投稿",
    "北海道假期旅行社",
    "每篇 NT$1,500",
    "提供冬季交通及景點情報",
  ],
  [
    "桃園在地導覽短影音",
    "影音創作",
    "桃園樂遊旅行社",
    "每支 NT$1,200～3,000",
    "拍攝在地景點短影音",
  ],
  [
    "線上領隊經驗分享講師",
    "線上講師",
    "旅遊人才學院",
    "每小時 NT$1,500",
    "分享帶團流程與突發事件處理",
  ],
  [
    "旅遊服務神秘客",
    "體驗任務",
    "旅遊品質研究中心",
    "每次 NT$800～2,500",
    "完成指定服務體驗與問卷",
  ],
  [
    "推薦專業領隊加入",
    "推薦獎勵",
    "平台推薦計畫",
    "每位 NT$500",
    "推薦符合資格的領隊完成註冊",
  ],
  [
    "韓國交通情報協作",
    "文章投稿",
    "東亞旅遊研究室",
    "每篇 NT$1,200",
    "整理韓國大眾運輸實用資訊",
  ],
  [
    "親子旅遊線上顧問",
    "行程顧問",
    "島嶼探索旅遊",
    "每案 NT$3,000",
    "提供親子旅遊動線建議",
  ],
  [
    "旅遊裝備開箱任務",
    "影音創作",
    "旅行裝備研究所",
    "每件 NT$2,000",
    "拍攝旅遊裝備實測內容",
  ],
  [
    "城市導覽教材共創",
    "線上講師",
    "在地知識學院",
    "每單元 NT$3,500",
    "共同製作城市導覽教材",
  ],
];
export const defaultIncome = incomeSeeds.map((s, i) => ({
  id: `income-${String(i + 1).padStart(3, "0")}`,
  title: s[0],
  category: s[1],
  partnerName: s[2],
  reward: s[3],
  summary: s[4],
  role: ["leader", "guide"],
  workMode: i % 3 === 0 ? "線上" : "不限地點",
  deadline:
    i === 2 || i === 7
      ? "長期開放"
      : `2026-${i % 2 ? "11" : "10"}-${String(15 + i).padStart(2, "0")}`,
  remaining: i % 4 === 0 ? 5 : 12,
  featured: i < 3,
  status: "open",
  tags: [s[1], i < 3 ? "熱門推薦" : "彈性合作"],
  tasks: ["閱讀合作說明", "依指定格式提交內容", "配合前端 Demo 審核流程"],
  requirements: ["已完成會員資料", "同意提供公開個人簡介"],
}));
export const defaultFeatureState = {
  version: 2,
  profile: defaultProfile,
  jobs: defaultJobs,
  jobFavorites: [],
  jobFilters: {
    tab: "為你推薦",
    query: "",
    role: "all",
    area: "all",
    sort: "推薦排序",
  },
  applications: [],
  posts: defaultPosts,
  comments: defaultComments,
  postBookmarks: [],
  discussion: {
    category: "全部",
    query: "",
    sort: "推薦",
    view: "card",
    draft: null,
    rulesAccepted: false,
  },
  income: defaultIncome,
  incomeFavorites: [],
  incomeFilters: {
    category: "全部",
    query: "",
    workMode: "全部",
    rewardKeyword: "",
    sort: "推薦排序",
  },
  incomeJoins: [],
  earnings: [
    {
      id: "earning-001",
      opportunityId: "income-001",
      title: "北海道冬季帶團注意事項",
      amount: 1500,
      status: "可領取",
      completedAt: "2026-08-20",
      settlementDate: "2026-09-05",
    },
    {
      id: "earning-002",
      opportunityId: "income-005",
      title: "桃園老街短影音",
      amount: 1200,
      status: "待審核",
      completedAt: "2026-08-27",
      settlementDate: "2026-09-15",
    },
  ],
  notifications: [
    {
      id: "n1",
      type: "discussion",
      text: "有人回覆你的文章",
      target: "/discussion/post-001",
      read: false,
      time: "剛剛",
    },
    {
      id: "n2",
      type: "job",
      text: "收藏的徵才即將截止",
      target: "/jobs/job-003",
      read: false,
      time: "1小時前",
    },
  ],
  reports: [],
};
